name: GitHub Actions Demo
on:
  pull_request
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run tauri build
